# Generated by Django 3.1.3 on 2020-11-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201129_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categore',
            new_name='category',
        ),
    ]
