# Generated by Django 3.1.3 on 2020-12-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201129_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.DateTimeField(max_length=1000, null=True),
        ),
    ]
